config/routes.rb
Rails.application.routes.draw do

  resources :passwords, :only => [:new, :create, :edit, :update]
  post  '/login' => 'sessions#create'
  get   '/login' => 'sessions#new'
  get   '/logout' => 'sessions#destroy'

  resources :registrations
  resource  :user
  get '/verify-email/:email_verification_key' => 'users#verify_email', :as => :verify_email
  get '/resend-email-verification/:email_verification_key' => 'users#resend_email_verification', :as => :resend_email_verification
    
  resources :areas, :only => :show do
    get '/current-issue' => 'areas/issues#current', :as => :current_issue
    resources :issues, :controller => 'areas/issues', :only => [:index, :show] do
      collection do
        get '/:year/:month', :action => :index, :as => :archive
      end
    end
    resources :posts, :controller => 'areas/posts', :only => [:index, :new, :create]
  end
  
  namespace :admin do
    get '/' => redirect('/admin/areas')
    resources :areas do
      resources :issues, :controller => 'areas/issues' do
        member do
          post :add_posts
          post :remove_posts
        end
      end
      resources :posts, :controller => 'areas/posts' do
        member do
          post :toggle_reviewed_by
        end
        collection do
          put :order, :as => :order
        end
      end
      member do
        get :edit_borders
      end
      collection do
        post :bulk_update
      end
      resources :memberships, :controller => 'areas/memberships'
    end
    resources :users
    resources :user_activity
  end
  
  root :to => 'registrations#index'
  
end

app/controllers/admin/areas/base_controller.rb
class Admin::Areas::BaseController < Admin::BaseController
  before_filter :require_authority_to_manage_areas
  before_filter :load_area

protected
  def load_area
    @area = Area.find(params[:area_id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Area not found', :status => 404
  end
end

app/controllers/admin/areas/issues_controller.rb
class Admin::Areas::IssuesController < Admin::Areas::BaseController
  before_filter :load_issue,
    :except => [:index, :new]
  before_filter :block_edit_if_sent,
    :except => [:index, :new, :show]
  
  def index
    @issues = @area.issues.order("number DESC").paginate(:page => params[:page])
  end
  
  def new
    @issue = @area.issues.create!
    redirect_to edit_admin_area_issue_path(@area, @issue)
  end

  def edit
    load_posts
  end
  
  def show
    if @issue.sent_at.blank?
      redirect_to edit_admin_area_issue_path(@area, @issue)
    end
  end
  
  def update
    @issue.update_attributes!(params[:issue])
    redirect_to edit_admin_area_issue_path(@area, @issue)
  rescue ActiveRecord::RecordInvalid
    load_posts
    render :action => :edit
  end

  def add_posts
    return if params[:posts].blank?
    Post.update_all(['issue_id = %d', @issue.id], ['id IN (?)', params[:posts]])
  end

  def remove_posts
    return if params[:posts].blank?
    Post.update_all('issue_id = NULL', ['id IN (?)', params[:posts]])
  end
  
protected
  def load_area
    @area = Area.find(params[:area_id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Area not found.', :status => 404
  end

  def load_issue
    @issue = @area.issues.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Issue not found.', :status => 404
  end
  
  def load_posts
    @new_posts = @area.posts.in_issue(nil).order('created_at DESC')
    @issue_posts = @area.posts.in_issue(@issue).order('position')
  end
  
  def block_edit_if_sent
    if @issue.sent_at.present?
      redirect_to admin_area_issue_path(@area, @issue) 
    end
  end
end

app/controllers/admin/areas/memberships_controller.rb
class Admin::Areas::MembershipsController < Admin::Areas::BaseController

  def index
    @memberships =  @area.memberships.includes(:user)
  end

end

app/controllers/admin/areas/posts_controller.rb
class Admin::Areas::PostsController < Admin::Areas::BaseController
  respond_to :js
  before_filter :load_post,
    :except => :order
  
  def edit
  end
  
  def update
    @post.update_attributes(params[:post])
  end
  
  def show
  end
  
  def order
    if params[:post].present?
      params[:post].each_with_index do |post, i|
        Post.update_all(['position = %d', i], ['id = %d', post])
      end
    end
    render :nothing => true
  end
  
  def toggle_reviewed_by
    if !@post.reviewed_by
      @post.update_attribute(:reviewed_by, current_user.full_name)
    else
      @post.update_attribute(:reviewed_by, nil)
    end
    render :layout => false
  end
  
  def destroy
    @post.destroy
  end

protected
  def load_post
    @post = @area.posts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :nothing => true, :status => 404
  end
end

app/controllers/admin/areas_controller.rb
class Admin::AreasController < Admin::BaseController
  before_filter :require_authority_to_manage_areas
  before_filter :build_area,
    :only => [:new, :create]
  before_filter :load_area,
    :except => [:index, :new, :create, :edit_borders, :bulk_update]
    
  def index
    params[:search] ||= {}
    params[:search][:meta_sort] ||= 'city'
    @search = Area.search(params[:search])
    @areas = @search.paginate(:page => params[:page])
    @new_posts = Area.newposts_count
    
    start_date =  Time.parse(params[:activity_start_date]).to_date    rescue 30.days.ago.to_date
    end_date =    Time.parse(params[:activity_end_date]).to_date      rescue Date.today
    
    @activities = AreaActivity.grouped_by_day.search(:day_between => [start_date, end_date]).where(:area_id => @search.all.collect(&:id))
  end
  
  def new
  end
  
  def create
    @area.save!
    respond_to do |format|
      format.html do
        redirect_to([:admin, :areas], :notice => 'Area has been successfully created.')
      end
      format.js do
        render :text => @area.id
      end
    end
  rescue ActiveRecord::RecordInvalid
    render :action => :new
  end
  
  def show
    redirect_to [:edit, :admin, @area, @area.issues.last]
  end
  
  def edit
    # ...
  end
  
  def edit_borders
    @areas = Area.all
    @area = @selected_area = @areas.detect{|area| area.id == params[:id].to_i}
    if @selected_area.nil?
      @default_area = @areas.first
    end
  end
  
  def update
    @area.update_attributes!(params[:area])
    redirect_to([:admin, :areas], :notice => 'Area has been successfully updated.')
  rescue ActiveRecord::RecordInvalid
    render :action => :edit
  end
  
  def bulk_update
    params[:areas].each do |index, area_params|
      area = Area.find(area_params[:id])
      area.coordinates = area_params[:coordinates]
      area.save!
    end
    render :nothing => true
  rescue ActiveRecord::RecordInvalid
    render :nothing => true, :status => :bad_request
  end
  
  def destroy
    @area.destroy
    redirect_to([:admin, :areas], :notice => 'Area has been successfully deleted.')
  end

protected
  def build_area
    @area = Area.new(params[:area])
  end
  
  def load_area
    @area = Area.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Area not found', :status => 404
  end
end

app/controllers/area/base_controller.rb
class Area::BaseController < ApplicationController
  before_filter :load_area
  before_filter :initialize_search
  
protected
  def load_area
    @area = current_user.areas.find(params[:area_id] || params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Area not found', :status => 404
  end
  
  def initialize_search
    params[:search] ||= {}
    @search = @area.posts.search(params[:search])
  end
end

app/controllers/area/issues_controller.rb
class Area::IssuesController < Area::BaseController
  before_filter :load_issue,
    :only => :show
  
  def index
    if params[:year].present? and params[:month].present?
      @current_month = Time.parse([params[:year], params[:month], '01'].join('-')).to_date
    else
      @current_month = Date.today.beginning_of_month
    end
    @issues = @area.issues.sent.in_month(@current_month.strftime("%Y-%m")).order('sent_at DESC')
  end

  def show
    @prev_issue = @area.issues.find_by_number(@issue.number-1)
    @next_issue  = @area.issues.find_by_number(@issue.number+1)
  end
  
  def current
    @issue = @area.issues.sent.last
    if @issue.present?
      render :template => 'area/issues/show'
    else
      render :text => 'Issue not found', :status => 404
    end
  end

protected
  def load_issue
    @issue = @area.issues.sent.find_by_number!(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Issue not found', :status => 404
  end
  
end

app/controllers/area/posts_controller.rb
class Area::PostsController < Area::BaseController
  before_filter :build_post,
    :only => [:new, :create]
  
  def index
    params[:search] ||= {}
    @search = @area.posts.order('created_at DESC').joins(:issue).where('sent_at IS NOT NULL').search(params[:search])
    @posts = @search.paginate(:page => params[:page])
  end
  
  def new
  end
  
  def create
    @post.save!
    redirect_to(area_path(@area), :notice => 'Your message has been successfully posted.')
  rescue ActiveRecord::RecordInvalid
    render :action => :new
  end

protected
  
  def build_post
    @post = @area.posts.new(params[:post])
    @post.user = current_user
  end
  
end

app/controllers/areas/base_controller.rb
class Areas::BaseController < ApplicationController
  before_filter :load_area
  before_filter :initialize_search
  
protected
  def load_area
    if current_user.is_admin?
      @area = Area.find(params[:area_id] || params[:id])
    else
      @area = current_user.areas.find(params[:area_id] || params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The area you were looking for was not found"
    if current_user.areas.empty?
      redirect_to user_path
    else
      redirect_to area_path(current_user.areas.first)
    end
  end
  
  def initialize_search
    params[:search] ||= {}
    @search = @area.posts.search(params[:search])
  end
end

app/controllers/areas/issues_controller.rb
class Areas::IssuesController < Areas::BaseController
  before_filter :load_issue,
    :only => :show
  
  def index
    if params[:year].present? and params[:month].present?
      @current_month = Time.parse([params[:year], params[:month], '01'].join('-')).to_date
    else
      @current_month = Date.today.beginning_of_month
    end
    @issues = @area.issues.sent.in_month(@current_month.strftime("%Y-%m")).order('sent_at DESC')
  end

  def show
    @prev_issue = @area.issues.find_by_number(@issue.number-1)
    @next_issue  = @area.issues.find_by_number(@issue.number+1)
  end
  
  def current
    @issue = @area.issues.sent.last
    if @issue.present?
      render :template => 'areas/issues/show'
    else
      render :text => 'Issue not found', :status => 404
    end
  end

protected
  def load_issue
    @issue = @area.issues.sent.find_by_number!(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'Issue not found', :status => 404
  end
  
end

app/controllers/areas/posts_controller.rb
class Areas::PostsController < Areas::BaseController
  before_filter :build_post,
    :only => [:new, :create]
  
  def index
    params[:search] ||= {}
    @search = @area.posts.order('created_at DESC').joins(:issue).where('sent_at IS NOT NULL').search(params[:search])
    @posts = @search.paginate(:page => params[:page])
  end
  
  def new
  end
  
  def create
    @post.save!
    redirect_to(area_path(@area), :notice => 'Your message has been successfully posted.')
  rescue ActiveRecord::RecordInvalid
    render :action => :new
  end

protected
  
  def build_post
    @post = @area.posts.new(params[:post])
    @post.user = current_user
  end
  
end

app/controllers/areas_controller.rb
class AreasController < Areas::BaseController
  skip_before_filter :login_required, :only => :show
  before_filter :load_area, :only => :show
  before_filter :initialize_search

  def show
  end

protected
  def load_area
    if logged_in?
      if current_user.is_admin?
        @area = Area.find(params[:id])
      else
        @area = current_user.areas.find(params[:id])
      end
    else
      @session_user = SessionUser.new
      @area = Area.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The area you were looking for was not found"
    if current_user.areas.empty?
      redirect_to user_path
    else
      redirect_to area_path(current_user.areas.first)
    end
  end

end

app/views/admin/areas/_form.html.haml
= f.text_field :name
= f.text_field :slug
= f.text_area :description
= f.text_field :city
= f.text_field :state
= f.text_field :households
= f.select :send_mode, Area::SEND_MODES
= f.submit 'Save', :cancel_url => link_to('cancel', admin_areas_path)

app/views/admin/areas/_nav.html.haml
%ul.sub_nav
  %li
    %h3
      = @area.name
      in
      = @area.location
  - if @area.current_issue
    %li= active_link_to 'Current issue', [:edit, :admin, @area, @area.current_issue], :active => { :when => /admin\/areas\/\d*\/issues\/\d*\/edit/  }
  %li= active_link_to 'Issues', [:admin, @area, :issues], :active => { :when => :self_only }
  %li= active_link_to 'Memberships', [:admin, @area, :memberships]
  %li= active_link_to 'Edit borders', [:edit_borders, :admin, @area]
  %li= active_link_to 'Edit details', [:edit, :admin, @area], :active => { :when => :self_only }

app/views/admin/areas/edit.html.haml
.columns
  = render :partial => 'admin/areas/nav'
  
  .left_column

    = formatted_form_for @area, :url => [:admin, @area] do |f|
      = render :partial => 'form', :locals => {:f => f}
  
  
  .right_column

    - if @area.border.present?
      = content_for :head do
        = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false"
        = javascript_include_tag 'google_maps'
    
      = content_for :doc_ready do
        initialize_gmap(document.getElementById("map_canvas"), #{@area.center.x}, #{@area.center.y}, {}, #{@area.bounds.to_json});
        add_region(#{@area.id}, [#{@area.border_coordinates}], 'selected')

      #map_canvas{:style => 'width:260px; height:400px; float: right'}
  

app/views/admin/areas/edit_borders.html.haml
.columns
  = content_for :head do
    = javascript_include_tag "http://maps.google.com/maps/api/js?libraries=geometry&sensor=false"
    = javascript_include_tag 'region_editor'

  :javascript
    $(document).ready(function() {
      $('#map_canvas').RegionEditor({
        create_url: '#{admin_areas_path}',
        update_url: '#{bulk_update_admin_areas_path}',
        regions: #{@areas.collect(&:to_a).to_json}, 
        selected_region_id: #{@selected_area.present? ? @selected_area.id : 'null'},
        center: {
          lat: #{@selected_area.present? ? @selected_area.center.x : @default_area.center.x}, 
          lng: #{@selected_area.present? ? @selected_area.center.y : @default_area.center.y}
        },
        bounds: #{@selected_area.present? ? @selected_area.bounds.to_json : @default_area.bounds.to_json}
      });
    });
  - if @area.present?
    = render :partial => 'admin/areas/nav'

  #map_canvas
    .region_details

  %h3 Manage regions:
  %p 
    %strong 1. Click on a region to select it
    %br/
    %strong 2. Drag the markers to change the shape of a region
    %br/
    %strong 3. To add a new point to a region: 
    Right click on the map to add a new point to the selected region
    %br/
    %strong 4. To delete a point from a region:
    SHIFT + Click on a marker to delete it
  
  %h3 Create new regions:
  %p 
    %strong 1. Click the 'New region' button
    %br/
    %strong 2. Click on the map to add points to the region
    %br/
    %strong 3. When you're done close the region by clicking on the first marker

app/views/admin/areas/index.html.haml
.columns
  .header
    %h2 Areas
    = formatted_form_for @search, :url => [:admin, :areas], :html => {:method => :get, :class => 'admin_search'} do |f|
      = f.text_field :full_name_search, :label => 'name or location'
      = f.element('and show activity between') do
        = text_field_tag :activity_start_date,  params[:activity_start_date], :type => :date
        = text_field_tag :activity_end_date,    params[:activity_end_date], :type => :date
      = f.submit 'Find'
    %h5= link_to 'Add new area', edit_borders_admin_area_path('new')

  :javascript
    $(document).ready(function() {
      draw_chart({
        days : #{@activities.collect{|d| d.day.strftime('%d<br/>%b')}.to_json}, 
        series : [
          {
            name: 'New Users',
            data : #{@activities.collect{|a| a.sum_new_users_count.to_i}.to_json}
          }, 
          {
            name: 'Quitters',
            data : #{@activities.collect{|a| a.sum_quitters_count.to_i}.to_json}
          },
          {
            name: 'New Posts',
            data : #{@activities.collect{|a| a.sum_new_posts_count.to_i}.to_json}
          },
          {
            name: 'Issues Published',
            data : #{@activities.collect{|a| a.sum_issues_published_count.to_i}.to_json}
          }
        ]
      });
    })   
  #chart-container

  = will_paginate @areas

  %table
    %tr
      %th= sort_link @search, :name
      %th= sort_link @search, :city
      %th.center= sort_link @search, :memberships_count, 'Users'
      %th.center= sort_link @search, :households
      %th.center Send mode
      %th.center= sort_link @search, :issues_count, 'Issues'
      %th.center New posts
    
    - @areas.each do |area|
      %tr{:class => @new_posts[area.id] && @new_posts[area.id] > 0 ? 'important' : ''}
        %td= link_to area.name, [:edit_borders, :admin, area]
        %td= area.location
        %td.center= link_to area.memberships_count.to_i, [:admin, area, :memberships]
        %td.center= area.households.to_i
        %td.center= area.send_mode
        %td.center= link_to area.issues_count.to_i, [:admin, area, :issues]
        %td.center= link_to @new_posts[area.id].to_s, [:admin, area]

  = will_paginate @areas
  

app/views/admin/areas/new.html.haml
.columns
  %h1 Create new area

  = formatted_form_for @area, :url => [:admin, :areas] do |f|
    = render :partial => 'form', :locals => {:f => f}

app/views/admin/areas/new.js.haml
%h1 Create new region

= formatted_form_for @area, :url => [:admin, :areas] do |f|
  = render :partial => 'form', :locals => {:f => f}

app/views/admin/areas/show.html.haml
.columns
  %h2 #{@area.name} Neighbourhood Forum
  %h5
    = link_to 'Users', ''
    = link_to 'Issues', admin_area_issues_path(@area)